apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: st-website
spec:
  selector:
    app: apache
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
