apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeName: st22122101
      containers:
        - name: elasticsearch
          image: dikshaop/devops:exam-7-4-elasticsearch-test-1.1.1      
          ports:
            - containerPort: 9200
            - containerPort: 9300
      imagePullSecrets:
      - name: docker-registry-secret