apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay-deployment
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
      - image: dikshaop/devops:st-website-7-4-liferay-test-1.1.2
        name: liferay
        ports:
        - containerPort: 8009
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "1.5"
        volumeMounts:
        - mountPath: /opt/liferay/data
          name: liferay-data-volume
        - mountPath: /opt/liferay/tomcat/logs
          name: liferay-logs-volume
      imagePullSecrets:
      - name: docker-registry-secret
      nodeName: st04
      volumes:
      - name: liferay-data-volume
        persistentVolumeClaim:
          claimName: liferay-pvc-data
      - name: liferay-logs-volume
        persistentVolumeClaim:
          claimName: liferay-pvc-logs
