apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferay-deployment
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      nodeName: st04
      containers:
        - name: liferay
          image: dikshaop/devops:st-website-7-4-liferay-test-1.1.2
          resources:
            requests:
              cpu: "2"
            limits:
              cpu: "2"
          ports:
            - containerPort: 8009
          volumeMounts:
            - mountPath: /opt/liferay/data
              name: liferay-data-volume
            - mountPath: /opt/liferay/tomcat/logs
              name: liferay-logs-volume
      imagePullSecrets:
        - name: docker-registry-secret
      volumes:
        - name: liferay-logs-volume
          persistentVolumeClaim:
            claimName: liferay-pvc-logs
        - name: liferay-data-volume
          persistentVolumeClaim:
            claimName: liferay-pvc-data