apiVersion: v1
kind: Service
metadata:
  name: liferay-service
  namespace: exam
spec:
  selector:
    app: liferay
  ports:
    - name: ajp
      protocol: TCP
      port: 8009
      targetPort: 8009
