apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-pvc-data
  namespace: st-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-pvc-logs
  namespac  e: st-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi