apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      nodeName: st04
      containers:
      - name: mysql-deployment
        image: dikshaop/devops:st-exam-mysql-1244
        ports:
        - containerPort: 3306          
        volumeMounts:            
        - name: mysql-volume-longhorn
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: docker-registry-secret
      volumes: 
      - name: mysql-volume-longhorn
        persistentVolumeClaim:
          claimName: mysql-pvc-longhorn