apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: st-website
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /var/lib/mysql
 
