apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-longhorn
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-longhorn
  template:
    metadata:
      labels:
        app: mysql-longhorn
    spec:
      nodeName: st22122101
      containers:
      - name: mysql-longhorn
        image: dikshaop/devops:st-exam-mysql-1244
        ports:
        - containerPort: 3306          
        volumeMounts:            
        - name: mysql-volume-longhorn
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: docker-registry-secret
      volumes: 
      - name: mysql-volume-longhorn
        persistentVolumeClaim:
          claimName: mysql-longhorn