apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
  namespace: st-website
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/mysql/
 
