apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeName: st07061901
      containers:
      - name: mysql
        image: dikshaop/exam-mysql:latest
        ports:
        - containerPort: 3306          
        volumeMounts:            
        - name: mysql-volume
          mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: docker-registry-secret
      volumes: 
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
